name: Publish to NPM
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  # patch release
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install deps
        run: yarn install

      - name: Initialize git user
        run: |
          git config --global user.email "sjeong1127@gmail.com"
          git config --global user.name "Publish Workflow"

      - name: Initialize NPM configuration
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release patch update âœ¨
        if: ${{ contains(github.head_ref, 'patch') }}
        run: yarn patch
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release minor update ðŸš€
        if: ${{ contains(github.head_ref, 'feat') }}
        run: yarn minor
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: End message
        run: echo 'Done Release'
